### ISSUE TITLE
4th level is missing /job/ prefix

### ISSUE THREAD

**Issue by amaisano** [rondorn/CiPol#4]
Our 4th level requires "/job/my-job" in with the /job prefix to work, but it isn't being added. It's being added for all lower levels though. 

`https://jenkins.company.com/job/drupal/job/sw/job/vrc/job/vrc_ppd/` is the full path that works.

However, the app is resolving it to:

`https://jenkins.company.com/job/drupal/job/sw/job/vrc/vrc_ppd/` which doesn't work - no updates are being shown or polls made.

**Comment by rondorn** [comment]
Hmm, interesting.

Just saw this comment today. Let me look into this.

Thanks for posting. 

Let me see if I can replicate this behavior, if I can replicate the behavior, I can fix this. If I am unable to easily reproduce, then this might stay open for a bit.

**Comment by rondorn** [comment]
Ok, the issue was easily reproducible and there was an easy fix.

Sorry it took so long to see your message.

Version 1.13 has been submitted to the App Store today and is pending Apple's approval for general release.

Thanks for using the software!

**Comment by amaisano** [comment]
Thank you!

**Comment by rondorn** [comment]
The fix is now available in the App Store

**Comment by amaisano** [comment]
I just updated the app and the behavior still does not quite work.

When a job is double-clicked in the CiPol app:

`https://jenkins-mkt.dsone.3ds.com/job/drupal//job/sw//job/vrc/jobvrc_ppd` (INCORRECT/BROKEN)

But this is a very broken URL. There are double slash characters, and missing slash characters. Correct URL is:

`https://jenkins-mkt.dsone.3ds.com/job/drupal/job/sw/job/vrc/job/vrc_ppd/` (CORRECT)

And the app shows no change in polling status - always "Not Polled." Some bad regex in the app, maybe?

Am I misunderstand how these URLs are supposed to work? I would assume the app should be bringing me to the working, correct pipeline page in Jenkins. But it's just returning this 404 page:

```
HTTP ERROR 404 Not Found
URI:	/job/drupal//job/sw//job/vrc/jobvrc_ppd
STATUS:	404
MESSAGE:	Not Found
SERVLET:	Stapler
```

**Comment by rondorn** [comment]
Interesting? Are you sure you are running version version 1.0.13 (35)

Based on your original report I was able to reproduce the bug
The bug in the code was obvious and easily fixed...nothing tricky or mysterious

I am running the 1.013 right now and can no longer reproduce the issue.

Maybe I found and fixed a different bug? Or maybe the URL your using on your Jenkins if different from the one I am using for mine.

Please confirm the version you are running and I will look into this agin if needed

**Comment by amaisano** [comment]
```
CiPol
version 1.0.13 (35)
Written by Ron Dorn
©All Rights Reserved
Distributed via GPLv2 License
```

**Comment by rondorn** [comment]
One more question. Did you delete and re-add the job?That will be required, hopefully that’s the only issue. Sent from my iPhoneOn Oct 20, 2023, at 12:30 AM, Adamo Maisano ***@***.***> wrote:﻿
CiPol
version 1.0.13 (35)
Written by Ron Dorn
©All Rights Reserved
Distributed via GPLv2 License

**Comment by amaisano** [comment]
I completely removed all jobs and servers and added everything from scratch. So that wasn't it.

If you notice, the URLs are broken but now in a different way.

**Comment by rondorn** [comment]
OK, the investigation continuesSent from my iPadOn Oct 20, 2023, at 5:59 AM, Adamo Maisano ***@***.***> wrote:﻿
I completely removed all jobs and servers and added everything from scratch. So that wasn't it.
If you notice, the URLs are broken but now in a different way.

**Comment by amaisano** [comment]
Let me know if I can help!

**Comment by rondorn** [comment]
Ok, I think I have found and fixed the issue.

The double slash is not an issue, the extra slash is ignored. In fact the fix was to add another slash to the URL where it was missing.

For my companies Jenkins servers and for the public Apache servers this extra slash is NOT needed, but apparently for your servers it is.

Based on your details that you provided I am pretty sure this will resolve  your issue, I can verify it doesn't break anything existing and changes to the URL in a way that should resolve your issue.

Look for 1.0.14(36) in the next day or so

Removing and re-adding the job will be needed

**Comment by amaisano** [comment]
It's working now! Thank you!

**Comment by rondorn** [comment]
Glad we could get this all fixed!
